version: 2

models:
  - name: base_entity
    columns:
      - name: id
        tests:
          - not_null
          - unique

  - name: relationships
    columns:
      - name: entity_id
        tests:
          - relationships:
              to: ref('base_entity')
              field: id

  - name: names
    columns:
      - name: entity_id
        tests:
          - relationships:
              to: ref('base_entity')
              field: id

  - name: locations
    columns:
      - name: entity_id
        tests:
          - relationships:
              to: ref('base_entity')
              field: id
